Add tracking of player mods, score, passed status
hburn7/BanchoSharp pull request #7
Opened 2022-11-12 01:46 UTC by matte-ek

This PR adds mod, score and passed tracking for every player. It will also handle mods set within the room, such as Freemod or if the room is forcing any other mods.

Depends on https://github.com/hburn7/BanchoSharp/pull/6

2022-11-12 03:36 UTC, hburn7 requested changes
After these changes are made, every single check in that spaghetti monster of an if statement (my fault for starting it!) will need to be extracted to it's own boolean method. Currently this isn't testable.

edit: resolved in d1191de9319f9d1e464c644d5a2602300241376b

2022-11-12 03:36 UTC, hburn7 commented on BanchoSharp/Multiplayer/MultiplayerMods.cs
> +    public static string ToShortString(this Mods mods, bool showFreemod = true)
I think the name `ToAbbreviatedForm` works better here.

2022-11-12 03:36 UTC, hburn7 commented on BanchoSharp/Multiplayer/MultiplayerMods.cs
> +        var ret = "";
I would rather a `StringBuilder` object be used here, string appending takes up resources.

2022-11-12 03:36 UTC, hburn7 commented on BanchoSharp/Multiplayer/MultiplayerLobby.cs
> +		else if (banchoBotResponse.StartsWith("Players: "))
See #6

2022-11-12 03:36 UTC, hburn7 commented on BanchoSharp/Multiplayer/MultiplayerLobby.cs
> +			var info = banchoBotResponse.Length > (playerNameBegin + 16) ? banchoBotResponse[(playerNameBegin + 16)..] : null;
More descriptive name needed, not sure what this is.

2022-11-12 03:36 UTC, hburn7 commented on BanchoSharp/Multiplayer/MultiplayerLobby.cs
> +			var name = banchoBotResponse.Substring(playerNameBegin, 16).TrimEnd();
Please specify what object name is referring to in the variable name. e.g. `playerName`

2022-11-12 03:36 UTC, hburn7 commented on BanchoSharp/Multiplayer/MultiplayerPlayer.cs
> +	public bool? Passed { get; set; } = null;
The default value of a nullable value type is null, so no need to declare that here.

2022-11-13 15:00 UTC, hburn7 commented
I knew there'd be conflicts, please merge v1.2.0 into this PR branch.

2022-11-14 09:52 UTC, matte-ek reviewed
Since only auto pilot seems to have a 'special' name, I think an edge-case check is fine. If more mods comes up with different names, we should probably consider a better solution.

2022-11-15 17:32 UTC, hburn7 commented
This PR is stale, will close and have asked @matte-ek to reopen.

2022-11-15 17:32 UTC, closed without merging